module.exports = {
    extends: [
        'stylelint-config-recommended',
        'stylelint-a11y/recommended',
        'stylelint-prettier/recommended',
        'stylelint-config-prettier',
    ],
    plugins: [
        'stylelint-value-no-unknown-custom-properties',
        'stylelint-z-index-value-constraint',
        'stylelint-selector-no-empty',
        'stylelint-group-selectors',
        'stylelint-declaration-block-no-ignored-properties',
        'stylelint-high-performance-animation',
        'stylelint-selector-tag-no-without-class',
        'stylelint-images',
        'stylelint-a11y',
        'stylelint-prettier',
    ],
    rules: {
        'prettier/prettier': true,
        'at-rule-no-vendor-prefix': true,
        'no-unknown-animations': true,
        'media-feature-name-no-vendor-prefix': true,
        'selector-no-vendor-prefix': true,
        'declaration-block-no-redundant-longhand-properties': true,
        'value-no-vendor-prefix': true,
        'shorthand-property-no-redundant-values': true,
        'function-url-no-scheme-relative': true,
        'csstools/value-no-unknown-custom-properties': true,
        'plugin/z-index-value-constraint': {
            min: 1,
            max: 10,
        },
        'plugin/stylelint-selector-no-empty': true,
        'plugin/stylelint-group-selectors': true,
        'plugin/declaration-block-no-ignored-properties': true,
        'plugin/no-low-performance-animation-properties': true,
        'plugin/selector-tag-no-without-class': ['div', 'pre', 'span', 'meta', 'link', 'base'],
        'images/broken': true,
        'images/prefer-data-uri': 512,
        'a11y/content-property-no-static-value': true,
        'a11y/font-size-is-readable': true,
        'a11y/no-display-none': true,
        'a11y/no-obsolete-attribute': true,
        'a11y/no-obsolete-element': true,
    },
};
